AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ocr-service

  SAM Template for ocr-service

Parameters:
  FirebaseApiKey:
    Type: String
  FirebaseAuthDomain:
    Type: String
  FirebaseProjectId:
    Type: String
  FirebaseStorageBucket:
    Type: String
  FirebaseMessagingSenderId:
    Type: String
  FirebaseAppId:
    Type: String
  FirebaseMeasurementId:
    Type: String
  FirebaseAdminCreds:
    Type: String
  Stage:
    Type: String
  OcrEngine:
    Type: String
  TesseractWorkerPath:
    Type: String
  TesseractLangPath:
    Type: String
  TesseractCorePath:
    Type: String
  TesseractIsGzipped:
    Type: String
  TesseractOcrEngineMode:
    Type: String
  TextractAccessKey:
    Type: String
  TextractSecretAccessKey:
    Type: String
  TextractRegion:
    Type: String


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60    
    MemorySize: 2048

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    # LoggingConfig:
    #   LogFormat: JSON

    Environment:
      Variables:
        FirebaseApiKey: !Ref FirebaseApiKey
        FirebaseAuthDomain: !Ref FirebaseAuthDomain
        FirebaseProjectId: !Ref FirebaseProjectId
        FirebaseStorageBucket: !Ref FirebaseStorageBucket
        FirebaseMessagingSenderId: !Ref FirebaseMessagingSenderId
        FirebaseAppId: !Ref FirebaseAppId
        FirebaseMeasurementId: !Ref FirebaseMeasurementId
        FirebaseAdminCreds: !Ref FirebaseAdminCreds
        Stage: !Ref Stage
        OcrEngine: !Ref OcrEngine          
        TesseractWorkerPath: !Ref TesseractWorkerPath          
        TesseractLangPath: !Ref TesseractLangPath          
        TesseractCorePath: !Ref TesseractCorePath          
        TesseractIsGzipped: !Ref TesseractIsGzipped          
        TesseractOcrEngineMode: !Ref TesseractOcrEngineMode          
        TextractAccessKey: !Ref TextractAccessKey          
        TextractSecretAccessKey: !Ref TextractSecretAccessKey          
        TextractRegion: !Ref TextractRegion          

Resources:
  VerifyTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/functions/verify-token
      Handler: handler.main
      Runtime: nodejs18.x
    Metadata: # Manage esbuild properties
        BuildMethod: esbuild
        BuildProperties:
          Minify: true
          Target: es2020
          Sourcemap: true
          EntryPoints:
          - handler.ts
          External:
          - node_modules
          - aws-sdk
          - esbuild

  OcrServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}
      Auth:
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt VerifyTokenFunction.Arn
        DefaultAuthorizer: TokenAuthorizer

  ProcessImageFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: .
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        ProcessApi:
          Type: Api
          Properties:
            Path: /process
            Method: post
            RestApiId: !Ref OcrServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      SourcesContent: true
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - src/functions/images/process/handler.ts
        External:
        - node_modules
        - aws-sdk
        - .esbuild
        - .github
        - .serverless
        - ./src/tesseract

  TestTimeFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: .
      Handler: handler.main
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        ProcessApi:
          Type: Api
          Properties:
            Path: /test
            Method: get
            RestApiId: !Ref OcrServiceApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      SourcesContent: true
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - src/functions/test/handler.ts
        External:
        - node_modules
        - aws-sdk
        - .esbuild
        - .github
        - .serverless
        - ./src/tesseract
