name: Deploy Staging

on:
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}    
    - name: Create Common Parameter Overrides
      run: | 
        params=""
        params="Stage=staging ${params}"
        params="OcrEngine=textract ${params}"
        params="TesseractWorkerPath=null ${params}"
        params="TesseractLangPath=null ${params}"
        params="TesseractCorePath=null ${params}"
        params="TesseractIsGzipped=null ${params}"
        params="TesseractOcrEngineMode=null ${params}"
        params="FIREBASEApiKey=${{ secrets.FIREBASE_API_KEY_PRODUCTION }} ${params}"
        params="FIREBASEAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_PRODUCTION }} ${params}"
        params="FIREBASEProjectId=${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }} ${params}"
        params="FIREBASEStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_PRODUCTION }} ${params}"
        params="FIREBASEMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PRODUCTION }} ${params}"
        params="FIREBASEAppId=${{ secrets.FIREBASE_APP_ID_PRODUCTION }} ${params}"
        params="FIREBASEMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_PRODUCTION }} ${params}"
        params="FIREBASEAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_PRODUCTION }} ${params}"
        echo $params > parameters.cfg

    - run: npm ci

    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_STAGING }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_STAGING }}
        aws-region: us-west-1
    - run: sam build   

    - name: Deploy to us-east-1 (SAM Deploy)
      run: |
        PARAMETERS=$(cat parameters.cfg)
        sam deploy --stack-name ocr-service \
        --region us-east-1 \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides $PARAMETERS "TextractRegion=us-east-1"
        
    - name: Deploy to us-west-1 (SAM Deploy)
      run: |
        PARAMETERS=$(cat parameters.cfg)
        sam deploy --stack-name ocr-service \
        --region us-west-1 \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides $PARAMETERS "TextractRegion=us-west-1"