name: Deploy Dev PR

on:
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci

    # - name: serverless deploy
    #   uses: serverless/github-action@v3.1
    #   with:
    #     args: deploy --config serverless-tesseract.ts --stage dev-pr \
    #         --param="FIREBASE_ADMIN_CREDS=${{ secrets.FIREBASE_ADMIN_CREDS_JSON_DEV_PR }}" \
    #         --param="QUEUE_STAGE_NAME=devpr" \
    #         --param="TEXTRACT_REGION=us-east-1" \
    #         --param="OCR_ENGINE=textract"
    #   env:
    #     SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY }}

    

    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY }}
        aws-region: us-west-1
    - run: sam build

    
    
    - name: Create Common Parameter Overrides
      run: | 
        echo -n "\"Stage=devpr\" " >> parameters.cfg
        echo -n "\"OcrEngine=textract\" " >> parameters.cfg
        echo -n "\"TesseractWorkerPath=null\" " >> parameters.cfg
        echo -n "\"TesseractLangPath=null\" " >> parameters.cfg
        echo -n "\"TesseractCorePath=null\" " >> parameters.cfg
        echo -n "\"TesseractIsGzipped=null\" " >> parameters.cfg
        echo -n "\"TesseractOcrEngineMode=null\" " >> parameters.cfg
        echo -n "\"TextractAccessKey=${{ secrets.TEXTRACT_ACCESS_KEY_ID }}\" " >> parameters.cfg
        echo -n "\"TextractSecretAccessKey=${{ secrets.TEXTRACT_SECRET_ACCESS_KEY }}\" " >> parameters.cfg
        echo -n ""\FirebaseApiKey=${{ secrets.FIREBASE_API_KEY_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV_PR }}\"" >> parameters.cfg
        echo -n "\"FirebaseMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseAppId=${{ secrets.FIREBASE_APP_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV_PR }}\" " >> parameters.cfg
        echo -n "\"FirebaseAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_DEV_PR }}\" " >> parameters.cfg
      # Note the trailing space on each parameter.
        
    - run: |
        PARAMETERS=$(cat parameters.cfg)
        sam deploy --stack-name ocr-service-dev-pr \
        --region us-west-1 \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides $PARAMETERS "TextractRegion=us-west-1"
        
        
        
        
        
        
# \
#   "FirebaseApiKey=${{ secrets.FIREBASE_API_KEY_DEV_PR }}" \
#   "FirebaseAuthDomain=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV_PR }}" \
#   "FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID_DEV_PR }}" \
#   "FirebaseStorageBucket=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV_PR }}" \
#   "FirebaseMessagingSenderId=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV_PR }}" \
#   "FirebaseAppId=${{ secrets.FIREBASE_APP_ID_DEV_PR }}" \
#   "FirebaseMeasurementId=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV_PR }}" \
#   "FirebaseAdminCreds=${{ secrets.FIREBASE_ADMIN_CREDS_DEV_PR }}" \
#   "Stage=devpr" \
#   "OcrEngine=textract" \
#   "TesseractWorkerPath=null" \
#   "TesseractLangPath=null" \
#   "TesseractCorePath=null" \
#   "TesseractIsGzipped=null" \
#   "TesseractOcrEngineMode=null" \
#   "TextractAccessKey=${{ secrets.TEXTRACT_ACCESS_KEY_ID }}" \
#   "TextractSecretAccessKey=${{ secrets.TEXTRACT_SECRET_ACCESS_KEY }}" \
#   "TextractRegion=us-west-1"